var annotated_dup =
[
    [ "uniot", null, [
      [ "AppKit", "classuniot_1_1AppKit.html", "classuniot_1_1AppKit" ],
      [ "Array", "classuniot_1_1Array.html", "classuniot_1_1Array" ],
      [ "Button", "classuniot_1_1Button.html", null ],
      [ "CallbackEventListener", "classuniot_1_1CallbackEventListener.html", null ],
      [ "CallbackMQTTDevice", "classuniot_1_1CallbackMQTTDevice.html", null ],
      [ "CBORObject", "classuniot_1_1CBORObject.html", "classuniot_1_1CBORObject" ],
      [ "CBORStorage", "classuniot_1_1CBORStorage.html", null ],
      [ "ConfigCaptivePortal", "classuniot_1_1ConfigCaptivePortal.html", null ],
      [ "COSEMessage", "classuniot_1_1COSEMessage.html", null ],
      [ "Credentials", "classuniot_1_1Credentials.html", null ],
      [ "DataChannels", "classuniot_1_1DataChannels.html", null ],
      [ "Date", "classuniot_1_1Date.html", null ],
      [ "EventBus", "classuniot_1_1EventBus.html", null ],
      [ "EventEmitter", "classuniot_1_1EventEmitter.html", null ],
      [ "EventEntity", "classuniot_1_1EventEntity.html", null ],
      [ "EventListener", "classuniot_1_1EventListener.html", null ],
      [ "GlobalBufferMemoryManager", "classuniot_1_1GlobalBufferMemoryManager.html", null ],
      [ "GpioRegister", "classuniot_1_1GpioRegister.html", "classuniot_1_1GpioRegister" ],
      [ "ICOSESigner", "classuniot_1_1ICOSESigner.html", null ],
      [ "IEventBusConnectionKit", "classuniot_1_1IEventBusConnectionKit.html", null ],
      [ "IExecutor", "classuniot_1_1IExecutor.html", null ],
      [ "ISchedulerConnectionKit", "classuniot_1_1ISchedulerConnectionKit.html", null ],
      [ "IWithType", "classuniot_1_1IWithType.html", null ],
      [ "Lisp", "classuniot_1_1Lisp.html", null ],
      [ "LispDevice", "classuniot_1_1LispDevice.html", null ],
      [ "Map", "classuniot_1_1Map.html", "classuniot_1_1Map" ],
      [ "MQTTDevice", "classuniot_1_1MQTTDevice.html", null ],
      [ "MQTTKit", "classuniot_1_1MQTTKit.html", null ],
      [ "MQTTPath", "classuniot_1_1MQTTPath.html", null ],
      [ "NetworkController", "classuniot_1_1NetworkController.html", null ],
      [ "NetworkScheduler", "classuniot_1_1NetworkScheduler.html", null ],
      [ "ObjectRegister", "classuniot_1_1ObjectRegister.html", null ],
      [ "ObjectRegisterRecord", "classuniot_1_1ObjectRegisterRecord.html", null ],
      [ "PrimitiveExpeditor", "classuniot_1_1PrimitiveExpeditor.html", null ],
      [ "Register", "classuniot_1_1Register.html", "classuniot_1_1Register" ],
      [ "RegisterManager", "classuniot_1_1RegisterManager.html", null ],
      [ "RegisterManagerProxy", "classuniot_1_1RegisterManagerProxy.html", null ],
      [ "SchedulerTask", "classuniot_1_1SchedulerTask.html", null ],
      [ "SimpleNTP", "classuniot_1_1SimpleNTP.html", null ],
      [ "Singleton", "classuniot_1_1Singleton.html", null ],
      [ "Storage", "classuniot_1_1Storage.html", null ],
      [ "TaskScheduler", "classuniot_1_1TaskScheduler.html", null ],
      [ "TopDevice", "classuniot_1_1TopDevice.html", null ],
      [ "Type", "classuniot_1_1Type.html", null ],
      [ "unLisp", "classuniot_1_1unLisp.html", null ],
      [ "WifiStorage", "classuniot_1_1WifiStorage.html", null ]
    ] ],
    [ "Bytes", "classBytes.html", null ],
    [ "ClearQueue", "classClearQueue.html", "classClearQueue" ],
    [ "FourCC", "structFourCC.html", null ],
    [ "IterableQueue", "classIterableQueue.html", null ],
    [ "LimitedQueue", "classLimitedQueue.html", null ],
    [ "UniotCore", "classUniotCore.html", null ]
];